# Generated by Django 5.2.15 on 2026-07-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('scientific_name', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(help_text='توضیح کلی مکمل')),
                ('dosage', models.TextField(help_text='دوز توصیه\u200cشده - مثلاً: ۲۵ گرم در روز')),
                ('usage_instructions', models.TextField(help_text='نحوه و زمان مصرف - مثلاً: ۳۰ دقیقه قبل از تمرین')),
                ('benefits', models.TextField(help_text='مزایا و فواید')),
                ('side_effects', models.TextField(help_text='عوارض جانبی احتمالی')),
                ('warnings', models.TextField(help_text='هشدارها - مثلاً: برای افراد زیر ۱۸ سال مناسب نیست')),
                ('fda_reference', models.CharField(blank=True, help_text='مرجع FDA/سازمان غذا و دارو', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'supplements',
                'indexes': [models.Index(fields=['name'], name='supplements_name_782025_idx')],
            },
        ),
    ]
