# Generated by Django 5.2.15 on 2026-07-19 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('activity_type', models.CharField(choices=[('running', 'Running'), ('swimming', 'Swimming'), ('cycling', 'Cycling'), ('walking', 'Walking')], db_index=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=20)),
                ('value_goal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('goal_unit', models.CharField(choices=[('km', 'Kilometers'), ('minute', 'Minutes'), ('step', 'Steps'), ('calorie', 'Calories'), ('kg', 'Kilograms')], max_length=20)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('created_by', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'challenge',
                'ordering': ['-created_at'],
            },
        ),
    ]
