# Generated by Django 5.2.15 on 2026-07-21 11:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('rules', models.TextField(blank=True, max_length=2000, null=True)),
                ('competition_type', models.CharField(choices=[('weight_loss', 'Weight loss'), ('activity_based', 'Activity based'), ('record_based', 'Record based')], db_index=True, max_length=30)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished')], db_index=True, default='pending', max_length=20)),
                ('created_by', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'competition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(db_index=True, help_text='ID of the participant, taken from the X-User-Id header.')),
                ('value', models.DecimalField(decimal_places=2, help_text='Positive numeric value representing the recorded progress.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('activity_date', models.DateField(db_index=True, help_text='The date the activity actually took place.')),
                ('note', models.CharField(blank=True, help_text='Optional free-text note from the participant.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(help_text='Challenge this activity contributes progress to.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='team1.challenge')),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['user_id', 'challenge'], name='idx_activity_user_challenge'), models.Index(fields=['challenge', 'activity_date'], name='idx_activity_challenge_date')],
            },
        ),
    ]
