# Generated by Django 5.2.15 on 2026-07-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team1', '0002_competition_alter_challenge_status_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantScore',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_scores', to='team1.challenge')),
            ],
            options={
                'db_table': 'participant_score',
                'unique_together': {('challenge', 'user_id')},
            },
        ),
    ]
