# Generated by Django 5.2.15 on 2026-07-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team1', '0003_participantscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='team1.competition')),
            ],
            options={
                'db_table': 'competition_participant',
                'ordering': ['-joined_at'],
                'constraints': [models.UniqueConstraint(fields=('competition', 'user_id'), name='unique_competition_user')],
            },
        ),
    ]
