# Generated by Django 5.2.15 on 2026-07-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team1', '0004_competitionparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionparticipant',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='participantscore',
            index=models.Index(fields=['challenge', '-score'], name='idx_score_challenge'),
        ),
    ]
