# Generated by Django 5.2.15 on 2026-07-22 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team1', '0005_competitionparticipant_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('score_total', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='team1.challenge')),
            ],
            options={
                'db_table': 'participant_challenge',
                'constraints': [models.UniqueConstraint(fields=('challenge', 'user_id'), name='unique_challenge_user')],
            },
        ),
    ]
