# Generated by Django 5.2.15 on 2026-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team1', '0006_participantchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantchallenge',
            name='final_rank',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
