# Generated by Django 5.2.15 on 2026-07-22 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team1', '0007_participantchallenge_final_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('top1', 'Top 1'), ('top3', 'Top 3'), ('top10', 'Top 10')], max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reward',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='team1.challenge')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='team1.reward')),
            ],
            options={
                'db_table': 'user_badge',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'challenge', 'reward'), name='unique_user_badge')],
            },
        ),
    ]
